name: lz4_ffi
description: FFI bindings for the LZ4 compression algorithm library.
version: 1.0.0-dev.2
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/lz4_ffi
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: any
  crypto: ^3.0.7
  ffi: ^2.1.4
  hooks: any
  meta: ^1.17.0
  native_toolchain_c: any

dev_dependencies:
  deminearchiver_lints: ^1.1.1
  ffigen: ^20.1.1
  test: ^1.28.0
