name: workspace
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

workspace:
  - packages/androidx_graphics_shapes
  - packages/deminearchiver_lints
  - packages/device_info_ffi
  - packages/device_info_ffi/example
  - packages/dynamic_color_ffi
  - packages/dynamic_color_ffi/example
  - packages/layout
  - packages/material
  - packages/permissions_ffi
  - packages/permissions_ffi/example
  - packages/screen_corners_ffi
  - packages/screen_corners_ffi/example

dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
