name: libmonet
description: Algorithms and utilities that power the Material Design 3 (M3) color system, including choosing theme colors from images and creating tones of colors; all in a new color space.
version: 1.0.0-dev.2
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/libmonet
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.10.4
  collection: ^1.19.1
  deminearchiver_lints: ^1.1.1
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.3
  test: ^1.28.0
