name: package_info_ffi
description: An FFI-based version of the package_info_plus plugin.
version: 1.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/package_info_ffi
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^2.1.4
  file: ^7.0.1
  jni: ^0.15.2
  meta: ^1.17.0
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1
  win32: ^5.15.0
  win32_registry: ^2.1.0
  path: ^1.9.1
  clock: ^1.1.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^1.1.1
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: PackageInfoAndroid
        ffiPlugin: true
      linux:
        dartPluginClass: PackageInfoLinux
      windows:
        dartPluginClass: PackageInfoWindows
