name: shapes
description: "A new Flutter package project."
version: 1.0.0
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  meta: ^1.17.0
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^1.1.0
