name: dynamic_color_ffi
description: An FFI-based version of the dynamic_color plugin.
version: 1.0.0
homepage:
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.15.2
  meta: ^1.17.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^1.1.0
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: DynamicColorAndroid
        ffiPlugin: true
