name: device_info_ffi
description: An FFI-based version of the device_info_plus plugin.
version: 1.0.2
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/device_info_ffi
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^2.1.4
  file: ^7.0.1
  jni: ^0.15.2
  meta: ^1.17.0
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1
  win32: ^5.15.0
  win32_registry: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^1.1.0
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: DeviceInfoAndroid
        ffiPlugin: true
      linux:
        dartPluginClass: DeviceInfoLinux
      windows:
        dartPluginClass: DeviceInfoWindows
